version: '3.8'
#secrets:
#  db-name:
#    file: db-name.txt
#  db-user:
#    file: db-user.txt
#  db-password:
#    file: db-password.txt
#  db-url:
#    file: db-url.txt

secrets:
  db-name:
    external: true
  db-user:
    external: true
  db-password:
    external: true
  db-url:
    external: true

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    secrets:
      - 'db-name'
      - 'db-user'
      - 'db-password'
    environment:
#      - 'POSTGRES_DB=my-database'
#      - 'POSTGRES_USER=khamroev'
#      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_DB_FILE=/run/secrets/db-name'
      - 'POSTGRES_USER_FILE=/run/secrets/db-user'
      - 'POSTGRES_PASSWORD_FILE=/run/secrets/db-password'

  app:
    build: ./
#    container_name: 'spring-app'
    ports:
      - '8080:8080'
    secrets:
      - 'db-url'
      - 'db-user'
      - 'db-password'
    environment:
      - 'DB_URL_FILE=/run/secrets/db-url'
      - 'DB_USER_FILE=/run/secrets/db-user'
      - 'DB_PASSWORD_FILE=/run/secrets/db-password'
